### ISSUE TITLE
ISSUE!!!!

### ISSUE THREAD

**Issue by TheAzn123** [antonioddrivera/Guitar-Scales#3]
C# D minor is broken for Major and Minor :(

**Comment by antonioddrivera** [comment]
👍

**Comment by antonioddrivera** [comment]
The issue was rooted in a typo on the backend. The program would look use the selected key to search for the note on the fretboard, but it could never find it since the key and the note were slightly different in spelling. Will update program when I can

**Comment by antonioddrivera** [comment]
Fixed the bug and update the repo
